language: node_js
cache: 
  directories: 
    - ~/.npm
  node_js:
    - '14'
  git:
    deph: 3
  script:
    - yarn build
  deploy:
    provider: pages
    edge: true,
    skip-cleanup: true
    keep-history: true
    hithub-token: $GITHUB_TOKEN
    local-dir: dist/
    targetbranch: gh-pages
    commit_message: "Deploy Release"
    on:
      branch: main